import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'mr' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Landing Page
    'landing.welcome': 'Welcome to',
    'landing.appName': 'InfraTrace',
    'landing.tagline': 'Smart Construction Management',
    'landing.subtitle': 'Streamline your site operations with intelligent tracking',
    'landing.getStarted': 'Get Started',
    'landing.trusted': 'Trusted by construction teams across India',
    'landing.gps': 'GPS Tracking',
    'landing.realtime': 'Real-time Updates',
    'landing.team': 'Team Management',
    'landing.analytics': 'Analytics',
    
    // Login
    'login.title': 'Login',
    'login.selectRole': 'Select Your Role',
    'login.phoneNumber': 'Phone Number',
    'login.phonePlaceholder': 'Enter your phone number',
    'login.continue': 'Continue',
    'login.sendOTP': 'Send OTP',
    'login.verifyOTP': 'Verify OTP',
    'login.resendOTP': 'Resend OTP',
    'login.labour': 'Labour',
    'login.supervisor': 'Supervisor',
    'login.engineer': 'Engineer',
    'login.owner': 'Owner',
    'login.selectLanguage': 'Select Language',
    
    // Home
    'home.goodMorning': 'Good Morning',
    'home.goodAfternoon': 'Good Afternoon',
    'home.goodEvening': 'Good Evening',
    'home.markAttendance': 'Mark Attendance',
    'home.gpsRequired': 'GPS • Time • Live Photo Required',
    'home.synced': 'Synced',
    'home.yourTasks': 'Your Tasks',
    'home.pending': 'Pending',
    'home.site': 'Site',
    
    // Projects
    'projects.title': 'Projects',
    'projects.all': 'All',
    'projects.active': 'Active',
    'projects.completed': 'Completed',
    'projects.onHold': 'On Hold',
    'projects.progress': 'Progress',
    'projects.tasks': 'Tasks',
    'projects.members': 'Members',
    
    // Stats
    'stats.title': 'Statistics',
    'stats.attendance': 'Attendance',
    'stats.hoursWorked': 'Hours Worked',
    'stats.tasksOverview': 'Tasks Overview',
    'stats.thisMonth': 'This Month',
    'stats.completed': 'Completed',
    'stats.inProgress': 'In Progress',
    'stats.delayed': 'Delayed',
    'stats.weeklyPerformance': 'Weekly Performance',
    'stats.lastSevenDays': 'Last 7 Days',
    'stats.detailedMetrics': 'Detailed Metrics',
    'stats.daysPresent': 'Days Present',
    'stats.onTimeCheckins': 'On-Time Check-ins',
    'stats.sitesVisited': 'Sites Visited',
    'stats.performanceRating': 'Performance Rating',
    
    // Profile
    'profile.title': 'Profile',
    'profile.labour': 'Labour',
    'profile.supervisor': 'Supervisor',
    'profile.engineer': 'Engineer',
    'profile.owner': 'Owner',
    'profile.active': 'Active',
    'profile.phoneNumber': 'Phone Number',
    'profile.location': 'Location',
    'profile.language': 'Language',
    'profile.settings': 'Settings',
    'profile.helpSupport': 'Help & Support',
    'profile.about': 'About',
    'profile.logout': 'Logout',
    
    // Days
    'day.mon': 'Mon',
    'day.tue': 'Tue',
    'day.wed': 'Wed',
    'day.thu': 'Thu',
    'day.fri': 'Fri',
    'day.sat': 'Sat',
    'day.sun': 'Sun',
    
    // Features
    'feature.attendance': 'Mark Attendance',
    'feature.tasks': 'My Assigned Tasks',
    'feature.siteDocs': 'Site Documentation',
    'feature.chat': 'Chat with Supervisor',
    'feature.verify': 'Verify Attendance',
    'feature.assign': 'Assign Tasks',
    'feature.approve': 'Approve Work',
    'feature.access': 'Access Control',
    'feature.teamChat': 'Team Chat',
    'feature.onsite': 'On-site Verification',
    'feature.materials': 'Material Request',
    'feature.stock': 'Stock Tracking',
    'feature.approvals': 'Approvals',
    'feature.assignTask': 'Assign to Supervisor',
    'feature.communications': 'Communications',
    'feature.siteOwner': 'Construction Site Owner',
    'feature.payments': 'GST Invoice',
    'feature.stockManagement': 'Stock Management',
    'feature.dealer': 'Dealer Login',
    'feature.materialApprovals': 'Material Approvals',
    'feature.chatbot': 'AI Assistant',
    
    // Material Request
    'material.title': 'Material Request',
    'material.createNew': 'Create New Request',
    'material.materialName': 'Material Name',
    'material.quantity': 'Quantity',
    'material.unit': 'Unit',
    'material.priority': 'Priority',
    'material.reason': 'Reason',
    'material.submit': 'Submit Request',
    'material.myRequests': 'My Requests',
    'material.pendingApprovals': 'Pending Approvals',
    'material.approved': 'Approved',
    'material.rejected': 'Rejected',
    'material.pending': 'Pending',
    'material.low': 'Low',
    'material.medium': 'Medium',
    'material.high': 'High',
    'material.approve': 'Approve',
    'material.reject': 'Reject',
    
    // Stock
    'stock.title': 'Stock Management',
    'stock.adequate': 'Adequate',
    'stock.lowStock': 'Low',
    'stock.critical': 'Critical',
    'stock.reorderLevel': 'Reorder Level',
    'stock.location': 'Location',
    'stock.updated': 'Updated',
    
    // GST Invoice
    'gst.title': 'GST Invoice Generator',
    'gst.vendorDetails': 'Vendor Details',
    'gst.vendorName': 'Vendor Name',
    'gst.vendorGST': 'Vendor GST Number',
    'gst.billItems': 'Bill Items',
    'gst.itemName': 'Item Name',
    'gst.qty': 'Qty',
    'gst.rate': 'Rate',
    'gst.gstPercent': 'GST %',
    'gst.addItem': 'Add Another Item',
    'gst.generate': 'Generate Invoice',
    'gst.pastInvoices': 'Past Invoices',
    
    // Owner Dashboard
    'owner.dashboard': 'Owner Dashboard',
    'owner.revenue': 'Total Revenue',
    'owner.expenses': 'Total Expenses',
    'owner.profit': 'Net Profit',
    'owner.pending': 'Pending Bills',
    'owner.materialRequests': 'Material Requests',
    'owner.sitesOverview': 'Sites Overview',
    'owner.activeSites': 'Active Sites',
    'owner.totalWorkers': 'Total Workers',
    'owner.avgProgress': 'Avg. Progress',
    'owner.materialsStock': 'Materials Stock',
    'owner.monthlyExpenses': 'Monthly Expenses',
    'owner.labourWages': 'Labour Wages',
    'owner.materials': 'Materials',
    'owner.equipment': 'Equipment',
    'owner.utilities': 'Utilities',
    
    // Common
    'common.back': 'Back',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.loading': 'Loading',
  },
  hi: {
    // Landing Page
    'landing.welcome': 'स्वागत है',
    'landing.appName': 'इन्फ्राट्रेस',
    'landing.tagline': 'स्मार्ट निर्माण प्रबंधन',
    'landing.subtitle': 'बुद्धिमान ट्रैकिंग के साथ अपनी साइट संचालन को सुव्यवस्थित करें',
    'landing.getStarted': 'शुरू करें',
    'landing.trusted': 'भारत भर में निर्माण टीमों द्वारा विश्वसनीय',
    'landing.gps': 'जीपीएस ट्रैकिंग',
    'landing.realtime': 'रियल-टाइम अपडेट',
    'landing.team': 'टीम प्रबंधन',
    'landing.analytics': 'एनालिटिक्स',
    
    // Login
    'login.title': 'लॉगिन',
    'login.selectRole': 'अपनी भूमिका चुनें',
    'login.phoneNumber': 'फ़ोन नंबर',
    'login.phonePlaceholder': 'अपना फ़ोन नंबर दर्ज करें',
    'login.continue': 'जारी रखें',
    'login.sendOTP': 'ओटीपी भेजें',
    'login.verifyOTP': 'ओटीपी सत्यापित करें',
    'login.resendOTP': 'ओटीपी पुनः भेजें',
    'login.labour': 'मजदूर',
    'login.supervisor': 'पर्यवेक्षक',
    'login.engineer': 'इंजीनियर',
    'login.owner': 'मालिक',
    'login.selectLanguage': 'भाषा चुनें',
    
    // Home
    'home.goodMorning': 'सुप्रभात',
    'home.goodAfternoon': 'शुभ दोपहर',
    'home.goodEvening': 'शुभ संध्या',
    'home.markAttendance': 'उपस्थिति दर्ज करें',
    'home.gpsRequired': 'जीपीएस • समय • लाइव फोटो आवश्यक',
    'home.synced': 'समन्वयित',
    'home.yourTasks': 'आपके कार्य',
    'home.pending': 'लंबित',
    'home.site': 'साइट',
    
    // Projects
    'projects.title': 'परियोजनाएं',
    'projects.all': 'सभी',
    'projects.active': 'सक्रिय',
    'projects.completed': 'पूर्ण',
    'projects.onHold': 'रुकी हुई',
    'projects.progress': 'प्रगति',
    'projects.tasks': 'कार्य',
    'projects.members': 'सदस्य',
    
    // Stats
    'stats.title': 'आंकड़े',
    'stats.attendance': 'उपस्थिति',
    'stats.hoursWorked': 'काम के घंटे',
    'stats.tasksOverview': 'कार्य सारांश',
    'stats.thisMonth': 'इस महीने',
    'stats.completed': 'पूर्ण',
    'stats.inProgress': 'प्रगति में',
    'stats.delayed': 'विलंबित',
    'stats.weeklyPerformance': 'साप्ताहिक प्रदर्शन',
    'stats.lastSevenDays': 'पिछले 7 दिन',
    'stats.detailedMetrics': 'विस्तृत मेट्रिक्स',
    'stats.daysPresent': 'उपस्थित दिन',
    'stats.onTimeCheckins': 'समय पर चेक-इन',
    'stats.sitesVisited': 'साइट्स का दौरा',
    'stats.performanceRating': 'प्रदर्शन रेटिंग',
    
    // Profile
    'profile.title': 'प्रोफ़ाइल',
    'profile.labour': 'मजदूर',
    'profile.supervisor': 'पर्यवेक्षक',
    'profile.engineer': 'इंजीनियर',
    'profile.owner': 'मालिक',
    'profile.active': 'सक्रिय',
    'profile.phoneNumber': 'फ़ोन नंबर',
    'profile.location': 'स्थान',
    'profile.language': 'भाषा',
    'profile.settings': 'सेटिंग्स',
    'profile.helpSupport': 'सहायता और समर्थन',
    'profile.about': 'के बारे में',
    'profile.logout': 'लॉगआउट',
    
    // Days
    'day.mon': 'सोम',
    'day.tue': 'मंगल',
    'day.wed': 'बुध',
    'day.thu': 'गुरु',
    'day.fri': 'शुक्र',
    'day.sat': 'शनि',
    'day.sun': 'रवि',
    
    // Features
    'feature.attendance': 'उपस्थिति दर्ज करें',
    'feature.tasks': 'मेरे सौंपे गए कार्य',
    'feature.siteDocs': 'साइट दस्तावेज़',
    'feature.chat': 'पर्यवेक्षक से चैट करें',
    'feature.verify': 'उपस्थिति सत्यापित करें',
    'feature.assign': 'कार्य सौंपें',
    'feature.approve': 'काम स्वीकृत करें',
    'feature.access': 'एक्सेस नियंत्रण',
    'feature.teamChat': 'टीम चैट',
    'feature.onsite': 'साइट पर सत्यापन',
    'feature.materials': 'सामग्री अनुरोध',
    'feature.stock': 'स्टॉक ट्रैकिंग',
    'feature.approvals': 'अनुमोदन',
    'feature.assignTask': 'पर्यवेक्षक को सौंपें',
    'feature.communications': 'संचार',
    'feature.siteOwner': 'निर्माण स्थल मालिक',
    'feature.payments': 'जीएसटी चालान',
    'feature.stockManagement': 'स्टॉक प्रबंधन',
    'feature.dealer': 'डीलर लॉगिन',
    'feature.materialApprovals': 'सामग्री अनुमोदन',
    'feature.chatbot': 'एआई सहायक',
    
    // Material Request
    'material.title': 'सामग्री अनुरोध',
    'material.createNew': 'नया अनुरोध बनाएं',
    'material.materialName': 'सामग्री का नाम',
    'material.quantity': 'मात्रा',
    'material.unit': 'इकाई',
    'material.priority': 'प्राथमिकता',
    'material.reason': 'कारण',
    'material.submit': 'अनुरोध जमा करें',
    'material.myRequests': 'मेरे अनुरोध',
    'material.pendingApprovals': 'लंबित अनुमोदन',
    'material.approved': 'स्वीकृत',
    'material.rejected': 'अस्वीकृत',
    'material.pending': 'लंबित',
    'material.low': 'कम',
    'material.medium': 'मध्यम',
    'material.high': 'उच्च',
    'material.approve': 'स्वीकृत करें',
    'material.reject': 'अस्वीकार करें',
    
    // Stock
    'stock.title': 'स्टॉक प्रबंधन',
    'stock.adequate': 'पर्याप्त',
    'stock.lowStock': 'कम',
    'stock.critical': 'महत्वपूर्ण',
    'stock.reorderLevel': 'पुनः आदेश स्तर',
    'stock.location': 'स्थान',
    'stock.updated': 'अपडेट किया गया',
    
    // GST Invoice
    'gst.title': 'जीएसटी चालान जेनरेटर',
    'gst.vendorDetails': 'विक्रेता विवरण',
    'gst.vendorName': 'विक्रेता का नाम',
    'gst.vendorGST': 'विक्रेता जीएसटी नंबर',
    'gst.billItems': 'बिल आइटम',
    'gst.itemName': 'आइटम का नाम',
    'gst.qty': 'मात्रा',
    'gst.rate': 'दर',
    'gst.gstPercent': 'जीएसटी %',
    'gst.addItem': 'एक और आइटम जोड़ें',
    'gst.generate': 'चालान जेनरेट करें',
    'gst.pastInvoices': 'पिछले चालान',
    
    // Owner Dashboard
    'owner.dashboard': 'मालिक डैशबोर्ड',
    'owner.revenue': 'कुल राजस्व',
    'owner.expenses': 'कुल खर्च',
    'owner.profit': 'शुद्ध लाभ',
    'owner.pending': 'लंबित बिल',
    'owner.materialRequests': 'सामग्री अनुरोध',
    'owner.sitesOverview': 'साइट्स अवलोकन',
    'owner.activeSites': 'सक्रिय साइट्स',
    'owner.totalWorkers': 'कुल कर्मचारी',
    'owner.avgProgress': 'औसत प्रगति',
    'owner.materialsStock': 'सामग्री स्टॉक',
    'owner.monthlyExpenses': 'मासिक खर्च',
    'owner.labourWages': 'श्रमिक वेतन',
    'owner.materials': 'सामग्री',
    'owner.equipment': 'उपकरण',
    'owner.utilities': 'उपयोगिताएँ',
    
    // Common
    'common.back': 'वापस',
    'common.close': 'बंद करें',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.confirm': 'पुष्टि करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.view': 'देखें',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर करें',
    'common.sort': 'क्रमबद्ध करें',
    'common.success': 'सफलता',
    'common.error': 'त्रुटि',
    'common.loading': 'लोड हो रहा है',
  },
  mr: {
    // Landing Page
    'landing.welcome': 'स्वागत आहे',
    'landing.appName': 'इन्फ्राट्रेस',
    'landing.tagline': 'स्मार्ट बांधकाम व्यवस्थापन',
    'landing.subtitle': 'बुद्धिमान ट्रॅकिंगसह तुमच्या साइट ऑपरेशन्स सुव्यवस्थित करा',
    'landing.getStarted': 'सुरू करा',
    'landing.trusted': 'संपूर्ण भारतातील बांधकाम संघांद्वारे विश्वसनीय',
    'landing.gps': 'जीपीएस ट्रॅकिंग',
    'landing.realtime': 'रिअल-टाइम अपडेट',
    'landing.team': 'टीम व्यवस्थापन',
    'landing.analytics': 'विश्लेषण',
    
    // Login
    'login.title': 'लॉगिन',
    'login.selectRole': 'तुमची भूमिका निवडा',
    'login.phoneNumber': 'फोन नंबर',
    'login.phonePlaceholder': 'तुमचा फोन नंबर प्रविष्ट करा',
    'login.continue': 'पुढे चला',
    'login.sendOTP': 'ओटीपी पाठवा',
    'login.verifyOTP': 'ओटीपी सत्यापित करा',
    'login.resendOTP': 'ओटीपी पुन्हा पाठवा',
    'login.labour': 'कामगार',
    'login.supervisor': 'पर्यवेक्षक',
    'login.engineer': 'अभियंता',
    'login.owner': 'मालक',
    'login.selectLanguage': 'भाषा निवडा',
    
    // Home
    'home.goodMorning': 'सुप्रभात',
    'home.goodAfternoon': 'शुभ दुपार',
    'home.goodEvening': 'शुभ संध्याकाळ',
    'home.markAttendance': 'उपस्थिती नोंदवा',
    'home.gpsRequired': 'जीपीएस • वेळ • लाइव्ह फोटो आवश्यक',
    'home.synced': 'समक्रमित',
    'home.yourTasks': 'तुमची कार्ये',
    'home.pending': 'प्रलंबित',
    'home.site': 'साइट',
    
    // Projects
    'projects.title': 'प्रकल्प',
    'projects.all': 'सर्व',
    'projects.active': 'सक्रिय',
    'projects.completed': 'पूर्ण',
    'projects.onHold': 'थांबलेले',
    'projects.progress': 'प्रगती',
    'projects.tasks': 'कार्ये',
    'projects.members': 'सदस्य',
    
    // Stats
    'stats.title': 'आकडेवारी',
    'stats.attendance': 'उपस्थिती',
    'stats.hoursWorked': 'काम केलेले तास',
    'stats.tasksOverview': 'कार्य सारांश',
    'stats.thisMonth': 'या महिन्यात',
    'stats.completed': 'पूर्ण',
    'stats.inProgress': 'प्रगतीपथावर',
    'stats.delayed': 'विलंबित',
    'stats.weeklyPerformance': 'साप्ताहिक कामगिरी',
    'stats.lastSevenDays': 'गेले 7 दिवस',
    'stats.detailedMetrics': 'तपशीलवार मेट्रिक्स',
    'stats.daysPresent': 'उपस्थित दिवस',
    'stats.onTimeCheckins': 'वेळेवर चेक-इन',
    'stats.sitesVisited': 'साइट्सला भेट',
    'stats.performanceRating': 'कामगिरी रेटिंग',
    
    // Profile
    'profile.title': 'प्रोफाइल',
    'profile.labour': 'कामगार',
    'profile.supervisor': 'पर्यवेक्षक',
    'profile.engineer': 'अभियंता',
    'profile.owner': 'मालक',
    'profile.active': 'सक्रिय',
    'profile.phoneNumber': 'फोन नंबर',
    'profile.location': 'स्थान',
    'profile.language': 'भाषा',
    'profile.settings': 'सेटिंग्ज',
    'profile.helpSupport': 'मदत आणि समर्थन',
    'profile.about': 'बद्दल',
    'profile.logout': 'लॉगआउट',
    
    // Days
    'day.mon': 'सोम',
    'day.tue': 'मंगळ',
    'day.wed': 'बुध',
    'day.thu': 'गुरु',
    'day.fri': 'शुक्र',
    'day.sat': 'शनि',
    'day.sun': 'रवि',
    
    // Features
    'feature.attendance': 'उपस्थिती नोंदवा',
    'feature.tasks': 'माझी नियुक्त कार्ये',
    'feature.siteDocs': 'साइट दस्तऐवज',
    'feature.chat': 'पर्यवेक्षकाशी चॅट करा',
    'feature.verify': 'उपस्थिती सत्यापित करा',
    'feature.assign': 'कार्ये नियुक्त करा',
    'feature.approve': 'काम मंजूर करा',
    'feature.access': 'प्रवेश नियंत्रण',
    'feature.teamChat': 'टीम चॅट',
    'feature.onsite': 'साइटवर सत्यापन',
    'feature.materials': 'साहित्य विनंती',
    'feature.stock': 'स्टॉक ट्रॅकिंग',
    'feature.approvals': 'मंजुरी',
    'feature.assignTask': 'पर्यवेक्षकाला नियुक्त करा',
    'feature.communications': 'संप्रेषण',
    'feature.siteOwner': 'बांधकाम साइट मालक',
    'feature.payments': 'जीएसटी चलन',
    'feature.stockManagement': 'स्टॉक व्यवस्थापन',
    'feature.dealer': 'डीलर लॉगिन',
    'feature.materialApprovals': 'साहित्य मंजुरी',
    'feature.chatbot': 'एआय सहाय्यक',
    
    // Material Request
    'material.title': 'साहित्य विनंती',
    'material.createNew': 'नवीन विनंती तयार करा',
    'material.materialName': 'साहित्याचे नाव',
    'material.quantity': 'प्रमाण',
    'material.unit': 'युनिट',
    'material.priority': 'प्राधान्य',
    'material.reason': 'कारण',
    'material.submit': 'विनंती सबमिट करा',
    'material.myRequests': 'माझ्या विनंत्या',
    'material.pendingApprovals': 'प्रलंबित मंजुरी',
    'material.approved': 'मंजूर',
    'material.rejected': 'नाकारलेले',
    'material.pending': 'प्रलंबित',
    'material.low': 'कमी',
    'material.medium': 'मध्यम',
    'material.high': 'उच्च',
    'material.approve': 'मंजूर करा',
    'material.reject': 'नाकारा',
    
    // Stock
    'stock.title': 'स्टॉक व्यवस्थापन',
    'stock.adequate': 'पुरेसे',
    'stock.lowStock': 'कमी',
    'stock.critical': 'गंभीर',
    'stock.reorderLevel': 'पुन्हा ऑर्डर स्तर',
    'stock.location': 'स्थान',
    'stock.updated': 'अद्यतनित',
    
    // GST Invoice
    'gst.title': 'जीएसटी चलन निर्माता',
    'gst.vendorDetails': 'विक्रेता तपशील',
    'gst.vendorName': 'विक्रेताचे नाव',
    'gst.vendorGST': 'विक्रेता जीएसटी नंबर',
    'gst.billItems': 'बिल आयटम',
    'gst.itemName': 'वस्तूचे नाव',
    'gst.qty': 'प्रमाण',
    'gst.rate': 'दर',
    'gst.gstPercent': 'जीएसटी %',
    'gst.addItem': 'आणखी एक वस्तू जोडा',
    'gst.generate': 'चलन तयार करा',
    'gst.pastInvoices': 'मागील चलन',
    
    // Owner Dashboard
    'owner.dashboard': 'मालक डॅशबोर्ड',
    'owner.revenue': 'एकूण उत्पन्न',
    'owner.expenses': 'एकूण खर्च',
    'owner.profit': 'निव्वळ नफा',
    'owner.pending': 'प्रलंबित बिले',
    'owner.materialRequests': 'साहित्य विनंत्या',
    'owner.sitesOverview': 'साइट्स अवलोकन',
    'owner.activeSites': 'सक्रिय साइट्स',
    'owner.totalWorkers': 'एकूण कामगार',
    'owner.avgProgress': 'सरासरी प्रगती',
    'owner.materialsStock': 'साहित्य स्टॉक',
    'owner.monthlyExpenses': 'मासिक खर्च',
    'owner.labourWages': 'कामगार वेतन',
    'owner.materials': 'साहित्य',
    'owner.equipment': 'उपकरणे',
    'owner.utilities': 'उपयोगिता',
    
    // Common
    'common.back': 'मागे',
    'common.close': 'बंद करा',
    'common.save': 'जतन करा',
    'common.cancel': 'रद्द करा',
    'common.confirm': 'पुष्टी करा',
    'common.delete': 'हटवा',
    'common.edit': 'संपादित करा',
    'common.view': 'पहा',
    'common.search': 'शोधा',
    'common.filter': 'फिल्टर करा',
    'common.sort': 'क्रमवारी लावा',
    'common.success': 'यश',
    'common.error': 'त्रुटी',
    'common.loading': 'लोड होत आहे',
  },
  ta: {
    // Landing Page
    'landing.welcome': 'வரவேற்கிறோம்',
    'landing.appName': 'இன்ஃப்ராட்ரேஸ்',
    'landing.tagline': 'ஸ்மார்ட் கட்டுமான மேலாண்மை',
    'landing.subtitle': 'புத்திசாலித்தனமான கண்காணிப்புடன் உங்கள் தள செயல்பாடுகளை நெறிப்படுத்துங்கள்',
    'landing.getStarted': 'தொடங்குக',
    'landing.trusted': 'இந்தியா முழுவதும் கட்டுமான குழுக்களால் நம்பப்படுகிறது',
    'landing.gps': 'GPS கண்காணிப்பு',
    'landing.realtime': 'நிகழ்நேர புதுப்பிப்புகள்',
    'landing.team': 'குழு மேலாண்மை',
    'landing.analytics': 'பகுப்பாய்வு',
    
    // Login
    'login.title': 'உள்நுழைவு',
    'login.selectRole': 'உங்கள் பங்கை தேர்ந்தெடுக்கவும்',
    'login.phoneNumber': 'தொலைபேசி எண்',
    'login.phonePlaceholder': 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
    'login.continue': 'தொடரவும்',
    'login.sendOTP': 'OTP அனுப்பவும்',
    'login.verifyOTP': 'OTP சரிபார்க்கவும்',
    'login.resendOTP': 'OTP மீண்டும் அனுப்பவும்',
    'login.labour': 'தொழிலாளி',
    'login.supervisor': 'மேற்பார்வையாளர்',
    'login.engineer': 'பொறியாளர்',
    'login.owner': 'உரிமையாளர்',
    'login.selectLanguage': 'மொழியை தேர்ந்தெடுக்கவும்',
    
    // Home
    'home.goodMorning': 'காலை வணக்கம்',
    'home.goodAfternoon': 'மதிய வணக்கம்',
    'home.goodEvening': 'மாலை வணக்கம்',
    'home.markAttendance': 'வருகையை குறிக்கவும்',
    'home.gpsRequired': 'GPS • நேரம் • நேரடி புகைப்படம் தேவை',
    'home.synced': 'ஒத்திசைக்கப்பட்டது',
    'home.yourTasks': 'உங்கள் பணிகள்',
    'home.pending': 'நிலுவையில்',
    'home.site': 'தளம்',
    
    // Projects
    'projects.title': 'திட்டங்கள்',
    'projects.all': 'அனைத்தும்',
    'projects.active': 'செயலில்',
    'projects.completed': 'முடிந்தது',
    'projects.onHold': 'நிறுத்தப்பட்டது',
    'projects.progress': 'முன்னேற்றம்',
    'projects.tasks': 'பணிகள்',
    'projects.members': 'உறுப்பினர்கள்',
    
    // Stats
    'stats.title': 'புள்ளிவிவரங்கள்',
    'stats.attendance': 'வருகை',
    'stats.hoursWorked': 'வேலை செய்த மணிநேரம்',
    'stats.tasksOverview': 'பணிகள் கண்ணோட்டம்',
    'stats.thisMonth': 'இந்த மாதம்',
    'stats.completed': 'முடிந்தது',
    'stats.inProgress': 'முன்னேற்றத்தில்',
    'stats.delayed': 'தாமதமானது',
    'stats.weeklyPerformance': 'வாராந்திர செயல்திறன்',
    'stats.lastSevenDays': 'கடந்த 7 நாட்கள்',
    'stats.detailedMetrics': 'விரிவான அளவீடுகள்',
    'stats.daysPresent': 'வந்த நாட்கள்',
    'stats.onTimeCheckins': 'சரியான நேரத்தில் செக்-இன்',
    'stats.sitesVisited': 'பார்வையிட்ட தளங்கள்',
    'stats.performanceRating': 'செயல்திறன் மதிப்பீடு',
    
    // Profile
    'profile.title': 'சுயவிவரம்',
    'profile.labour': 'தொழிலாளி',
    'profile.supervisor': 'மேற்பார்வையாளர்',
    'profile.engineer': 'பொறியாளர்',
    'profile.owner': 'உரிமையாளர்',
    'profile.active': 'செயலில்',
    'profile.phoneNumber': 'தொலைபேசி எண்',
    'profile.location': 'இடம்',
    'profile.language': 'மொழி',
    'profile.settings': 'அமைப்புகள்',
    'profile.helpSupport': 'உதவி மற்றும் ஆதரவு',
    'profile.about': 'பற்றி',
    'profile.logout': 'வெளியேறு',
    
    // Days
    'day.mon': 'திங்',
    'day.tue': 'செவ்',
    'day.wed': 'புத',
    'day.thu': 'வியா',
    'day.fri': 'வெள்',
    'day.sat': 'சனி',
    'day.sun': 'ஞாயி',
    
    // Features
    'feature.attendance': 'வருகையை குறிக்கவும்',
    'feature.tasks': 'எனக்கு ஒதுக்கப்பட்ட பணிகள்',
    'feature.siteDocs': 'தள ஆவணங்கள்',
    'feature.chat': 'மேற்பார்வையாளருடன் அரட்டையடிக்கவும்',
    'feature.verify': 'வருகையை சரிபார்க்கவும்',
    'feature.assign': 'பணிகளை ஒதுக்குக',
    'feature.approve': 'வேலையை அங்கீகரிக்கவும்',
    'feature.access': 'அணுகல் கட்டுப்பாடு',
    'feature.teamChat': 'குழு அரட்டை',
    'feature.onsite': 'தள சரிபார்ப்பு',
    'feature.materials': 'பொருள் கோரிக்கை',
    'feature.stock': 'இருப்பு கண்காணிப்பு',
    'feature.approvals': 'அங்கீகாரங்கள்',
    'feature.assignTask': 'மேற்பார்வையாளருக்கு ஒதுக்குக',
    'feature.communications': 'தொடர்புகள்',
    'feature.siteOwner': 'கட்டுமான தள உரிமையாளர்',
    'feature.payments': 'GST விலைப்பட்டியல்',
    'feature.stockManagement': 'இருப்பு மேலாண்மை',
    'feature.dealer': 'டீலர் உள்நுழைவு',
    'feature.materialApprovals': 'பொருள் அங்கீகாரங்கள்',
    'feature.chatbot': 'AI உதவியாளர்',
    
    // Material Request
    'material.title': 'பொருள் கோரிக்கை',
    'material.createNew': 'புதிய கோரிக்கையை உருவாக்குக',
    'material.materialName': 'பொருளின் பெயர்',
    'material.quantity': 'அளவு',
    'material.unit': 'அலகு',
    'material.priority': 'முன்னுரிமை',
    'material.reason': 'காரணம்',
    'material.submit': 'கோரிக்கையை சமர்ப்பிக்கவும்',
    'material.myRequests': 'எனது கோரிக்கைகள்',
    'material.pendingApprovals': 'நிலுவையில் உள்ள அங்கீகாரங்கள்',
    'material.approved': 'அங்கீகரிக்கப்பட்டது',
    'material.rejected': 'நிராகரிக்கப்பட்டது',
    'material.pending': 'நிலுவையில்',
    'material.low': 'குறைவு',
    'material.medium': 'நடுத்தரம்',
    'material.high': 'அதிகம்',
    'material.approve': 'அங்கீகரிக்கவும்',
    'material.reject': 'நிராகரிக்கவும்',
    
    // Stock
    'stock.title': 'இருப்பு மேலாண்மை',
    'stock.adequate': 'போதுமான',
    'stock.lowStock': 'குறைவு',
    'stock.critical': 'முக்கியமான',
    'stock.reorderLevel': 'மீண்டும் ஆர்டர் நிலை',
    'stock.location': 'இடம்',
    'stock.updated': 'புதுப்பிக்கப்பட்டது',
    
    // GST Invoice
    'gst.title': 'GST விலைப்பட்டியல் உருவாக்கி',
    'gst.vendorDetails': 'விற்பனையாளர் விவரங்கள்',
    'gst.vendorName': 'விற்பனையாளர் பெயர்',
    'gst.vendorGST': 'விற்பனையாளர் GST எண்',
    'gst.billItems': 'பில் பொருட்கள்',
    'gst.itemName': 'பொருளின் பெயர்',
    'gst.qty': 'அளவு',
    'gst.rate': 'விலை',
    'gst.gstPercent': 'GST %',
    'gst.addItem': 'மற்றொரு பொருளைச் சேர்க்கவும்',
    'gst.generate': 'விலைப்பட்டியலை உருவாக்குக',
    'gst.pastInvoices': 'கடந்த விலைப்பட்டியல்கள்',
    
    // Owner Dashboard
    'owner.dashboard': 'உரிமையாளர் டாஷ்போர்டு',
    'owner.revenue': 'மொத்த வருவாய்',
    'owner.expenses': 'மொத்த செலவுகள்',
    'owner.profit': 'நிகர லாபம்',
    'owner.pending': 'நிலுவையில் உள்ள பில்கள்',
    'owner.materialRequests': 'பொருள் கோரிக்கைகள்',
    'owner.sitesOverview': 'தளங்கள் கண்ணோட்டம்',
    'owner.activeSites': 'செயலில் உள்ள தளங்கள்',
    'owner.totalWorkers': 'மொத்த தொழிலாளர்கள்',
    'owner.avgProgress': 'சராசரி முன்னேற்றம்',
    'owner.materialsStock': 'பொருட்கள் இருப்பு',
    'owner.monthlyExpenses': 'மாதாந்திர செலவுகள்',
    'owner.labourWages': 'தொழிலாளர் ஊதியங்கள்',
    'owner.materials': 'பொருட்கள்',
    'owner.equipment': 'உபகரணங்கள்',
    'owner.utilities': 'பயன்பாடுகள்',
    
    // Common
    'common.back': 'பின்னால்',
    'common.close': 'மூடு',
    'common.save': 'சேமி',
    'common.cancel': 'ரத்துசெய்',
    'common.confirm': 'உறுதிப்படுத்து',
    'common.delete': 'நீக்கு',
    'common.edit': 'திருத்து',
    'common.view': 'பார்',
    'common.search': 'தேடு',
    'common.filter': 'வடிகட்டு',
    'common.sort': 'வரிசைப்படுத்து',
    'common.success': 'வெற்றி',
    'common.error': 'பிழை',
    'common.loading': 'ஏற்றுகிறது',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
